### ISSUE TITLE
Quando o Elo7 terá uma API pública?

### ISSUE THREAD

**Issue by lincolnbrito** [elo7/tech-blog#220]
Estou desenvolvendo um serviço que ficaria lindo consumindo uma API do Elo7. Vocês pretendem disponibilizar uma API? Quando?

**Comment by FernandaBernardo** [comment]
Temos em backlog de disponibilizar API pública, porém ela ainda não está priorizada e não consigo lhe estimar quando ela estaria disponível.

**Comment by hugows** [comment]
bump

**Comment by leandrohonorio7** [comment]
Possuem alguma estimativa para disponibilizar a API agora?

**Comment by davibbsilva** [comment]
Temos alguns clientes de e-commerce aguardando isso também.

**Comment by ocarloslopes** [comment]
2021... Alguma previsão?

**Comment by leandrohonorio7** [comment]
Continuamos com esperanças ...

**Comment by lincolnbrito** [comment]
@FernandaBernardo como não está mais no elo7 sabe de alguém que possa nos dar uma previsão?

**Comment by gucarletto** [comment]
Eu também tenho uma ferramenta que gostaria de integrar caso houvesse essa API

**Comment by pauloamorimbr** [comment]
Nada ainda? Tenho um controle de estoque de produtos próprio e o ideal seria plugar isso na Elo7. Não há uma API ainda?

**Comment by vihhcunha** [comment]
Estou desenvolvendo um sistema com catálogo e estoque. Uma API pública seria muito interessante. Alguma previsão?

**Comment by lincolnbrito** [comment]
Talvez depois dessa compra pelo Etsy eles disponbilizem.
