### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by rapahaeru** [elo7/tech-blog#9]
Adicionar plugin para RSS

Sugestão:
* https://github.com/hurrymaplelad/docpad-plugin-rss

@FernandaBernardo @tcelestino

**Comment by tcelestino** [comment]
Além de adicionar o RSS e aproveitei para fazer um fix na exibição do objeto `{{site...}}` que não estava funcionando e coloquei o ano do rodapé para ser dinamicamente.
